aws_region          = "ap-south-1"
project_name        = "zomato"
project_environment = "production"
instance_type       = "t3.micro"
instance_ami        = "ami-0f559c3642608c138"
domain = "athul.shop"
hostname = "terraform-webserver"
